[package]
name = "linux_user_group"
version = "0.1.0"
authors = [ "mahkoh" ]

[lib]
name = "linux_user_group"

[dependencies.linux_core]
path = "../linux_core"

[dependencies.linux_file]
path = "../linux_file"
