[package]
name = "linux_process"
version = "0.1.0"
authors = [ "various" ]

[lib]
name = "linux_process"
path = "lib.rs"

[features]
default = ["retry"]
retry = []

[dependencies.linux_user_group]
path = "../user_group"

[dependencies.linux_core]
path = "../core"
