[package]
name = "linux_dir"
version = "0.1.0"
authors = [ "various" ]

[lib]
name = "linux_dir"
path = "lib.rs"

[features]
default = ["retry"]
retry = []

[dependencies.linux_file]
path = "../file"

[dependencies.linux_core]
path = "../core"
